baseURL = 'https://gowt.dev/'
languageCode = 'en-us'
title = "Home"
theme = "archie"
paginate = 4

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Topics"
    url = "/tags/"
    weight = 2

[taxonomies]
  tag = "tags"

[params]
  customCSS = ["css/custom.css"]
  showdate = false