baseURL = 'https://github.com/Gowtham-Mahendran/blog
languageCode = 'en-us'
title = "Blog"
theme = "archie"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Topics"
    url = "/tags/"
    weight = 2

[taxonomies]
  tag = "tags"
